changes to support neo4j 5.10.0
GSK-Biostatistics/neointerface pull request #29
Opened 2023-08-11 06:22 UTC by PranjaliParnerkar

@paltusplintus Please review!
@KWLgsk @Vidhisri56 FYI.

This PR is for this [PBI](https://dev.azure.com/DevOps-RD/Clinical%20Linked%20Data%20Experiments/_sprints/taskboard/Clinical%20Linked%20Data%20Experiments%20Team/Clinical%20Linked%20Data%20Experiments/Sprint%2011.7).

The changes have been made as per neo4j 5.10.0 with backward compatibility.

NOTE: The test cases for rdf_support are not working currently as it requires n10 plugin support which is not there currently so unable to test it.

2023-08-16 10:04 UTC, paltusplintus requested changes
@PranjaliParnerkar Thanks for the updates! please see some proposals below.

2023-08-16 10:04 UTC, paltusplintus commented on tests/test_json.py
> +        f' {{"type":"relationship","id":"{rel_id_1}","label":"LOVES","start":{{"id":"{node_id1}","labels":["User"],"properties":{{"name":"Eve"}}}},"end":{{"id":"{node_id2}","labels":["User"],"propert
make sure the test also works on 4.x

2023-08-17 06:46 UTC, PranjaliParnerkar commented on neointerface/neointerface.py
> +           yield name, type
│"id"│"name"│"type"│"entityType"│"labelsOrTypes"│"properties"│"ownedIndex"│"propertyType" |

These are the details we are getting from SHOW CONSTRAINTS. Shall I use all of them?

2023-08-22 07:47 UTC, PranjaliParnerkar commented
@paltusplintus I have made the changes as per comments.

2023-08-22 08:02 UTC, PranjaliParnerkar commented
There will be few more changes in Neointerface, got some issue while testing tab2neo. Moving this to draft for now.

2023-08-24 05:48 UTC, PranjaliParnerkar commented
@paltusplintus Please review!

2023-08-24 08:53 UTC, paltusplintus approved these changes

2023-08-24 08:53 UTC, merged